name: bert-clir
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - asyncpg=0.20.1
  - click=7.0
  - fuzzywuzzy=0.17.0
  - gensim=3.8.1
  - lark-parser=0.6.6
  - lxml=4.4.2
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=0.25.3
  - psycopg2=2.8.4
  - python-levenshtein=0.12.0
  - pudb=2019.2
  - pytest=5.3.5
  - pytest-cov=2.8.1
  - PyYAML=5.3
  - scikit-learn=0.22.1
  - scikit-sparse=0.4.4
  - spacy=2.2.3
  - sqlalchemy=1.3.13
  - pytorch::pytorch=1.3.1
  - tqdm=4.42.1
  - unidecode=1.1.1
  - xgboost=0.90
  - pip
  - pip:
      - anytree==2.6.0
      - datasketch==1.5.0
      - jsons==1.0.0
      - pytest-pudb==0.7.0
      - truepy==2.0.3
      - mysql-connector-python==8.0.19
      - bert-serving-server==1.10.0
      - bert-serving-client==1.10.0